ENH: IOC with lint + test docs generation

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -4,12 +4,137 @@ on: [push, pull_request]
 jobs:
   lint:
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        # The following allows for each run step to utilize ~/.bash_profile
+        # for setting up the per-step initial state.
+        # --login: a login shell. Source ~/.bash_profile
+        # -o pipefail: piped processes are important; fail if they fail
+        shell: bash --login -o pipefail {0}
+
     steps:
       - name: Check out repository code
         uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+          submodules: 'recursive'
+
       - name: Add the problem matcher
         run: |
           echo "::add-matcher::.github/workflows/matcher.json"   
-      - name: Make up a problem
+
+      - name: Install Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+
+      - name: Install whatrecord
         run: |
-          echo "iocBoot/ioc-test/st.cmd: line 1, col 1, Error - nonsensical. (no-confusion)"
+          python -m pip install whatrecord
+
+      - name: Parse the startup script
+        run: |
+          python -m whatrecord parse iocBoot/ioc-test/st.cmd --output-format=json | python iocBoot/ioc-test/lint_formatter.py
+
+  docs:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        # The following allows for each run step to utilize ~/.bash_profile
+        # for setting up the per-step initial state.
+        # --login: a login shell. Source ~/.bash_profile
+        # -o pipefail: piped processes are important; fail if they fail
+        shell: bash --login -o pipefail {0}
+
+    steps:
+      - name: Check out repository code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+          submodules: 'recursive'
+
+      - name: Install Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+
+      - name: Install whatrecord
+        run: |
+          # python -m pip install whatrecord
+          python -m pip install git+https://github.com/klauer/whatrecord@fix_offline
+          # Optional extras:
+          python -m pip install happi  # blark pytmc blark
+
+      - name: Dump offline information from whatrecord
+        run: |
+          python -m whatrecord server \
+            --gateway-config "./support/gateway" \
+            --scripts iocBoot/ioc*/*.cmd \
+            --dump-for-offline-usage support/docs/cache.json.gz \
+            ;
+
+      - name: Copy over the frontend pages
+        run: |
+          # TODO: frontend not distributed in whatrecord package yet; d'oh
+          # WHATRECORD_PATH=$(python -c "import os, whatrecord; print(os.path.dirname(whatrecord.__file__));")
+
+          mkdir -p .docs/dist
+          cp -R support/whatrecord/frontend/* .docs/
+          cp support/docs/docs_env .docs/.env
+
+      - name: Install yarn to build the frontend pages
+        run: |-
+          curl -fsSL --create-dirs -o $HOME/bin/yarn \
+          https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn-1.22.19.js
+          chmod +x $HOME/bin/yarn
+          echo "$HOME/bin" >> $GITHUB_PATH
+
+      # - name: Setup node
+      #   uses: actions/setup-node@v3
+      #   with:
+      #     node-version: 16
+      #     cache: 'yarn'
+
+      - name: Yarn build
+        run: |
+          cd .docs
+          yarn install
+          yarn build
+          cp ../support/docs/cache.json.gz dist/
+
+      - name: Display structure of documentation
+        run: ls -R
+        working-directory: .docs
+
+      - name: Upload documentation as artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: ${{ github.repository_owner }} ${{ github.event.repository.name }} Docs
+          path: .docs/dist
+
+  docs-deploy:
+    needs: docs
+
+    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
+    permissions:
+      pages: write      # to deploy to Pages
+      id-token: write   # to verify the deployment originates from an appropriate source
+
+    # Deploy to the github-pages environment
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download documentation artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: ${{ github.repository_owner }} ${{ github.event.repository.name }} Docs
+          path: .
+      - name: Display structure of documentation
+        run: ls -R
+        working-directory: .
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v2
